url: https://russian-language-list.nuhub.net
title: Russian Language List
description: List of resources for studying and teaching the Russian language
author_name: David Chappell
author_photo: /assets/images/author.jpg
author_blurb: The author has more than two decades of experience learning and teaching Russian.
google_analytics: UA-48777822-6
google_ad_client: ca-pub-9697496962185999
google_ad_slot: 4238015419
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/images/petersburg-1200x500.jpg
      image_alt: A scene in St. Petersburg at night with pedestrians and a trolleybuses
      image_credit: shbs (Pixabay) 
      
