url: https://russian-language-list.nuhub.net
title: Russian Language List
description: List of resources for studying and teaching the Russian language
authors:
  "David Chappell":
    photo: /assets/images/author.jpg
    blurb: >
      Started learning Russian in 1995 after comming in contact with the
      Russian-speaking community in New England. He became fluent in 2002 and
      now speaks it at home. He enjoys teaching the language and creating
      teaching tools.
google_analytics: UA-48777822-6
google_ad_client: ca-pub-9697496962185999
google_ad_slot: 4238015419
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/images/petersburg-1200x500.jpg
      image_alt: A scene in St. Petersburg at night with pedestrians and a trolleybuses
      image_credit: shbs (Pixabay) 
      
